name: Expose Local Server with Ngrok

on:
  push:
    branches:
      - main

jobs:
  expose_with_ngrok:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download ngrok binary
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive -Path ngrok.zip -DestinationPath .
        Remove-Item ngrok.zip

    - name: Expose local server with Ngrok
      run: |
        .\ngrok.exe http 8080  # Replace 8080 with the port of your local server
