name: Update Ngrok and Expose Local Server

on:
  push:
    branches:
      - main

jobs:
  update_and_expose_with_ngrok:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/ngrok

    - name: Authenticate with ngrok
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Update ngrok
      run: |
        ngrok update

    - name: Run ngrok HTTP
      run: |
        ngrok http 80
