name: Expose Local Server with Ngrok

on:
  push:
    branches:
      - main

jobs:
  expose_with_ngrok:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with ngrok
      run: .\ngrok.exe authtoken 2ZFh8a1Nk8d9awIHeTP6disHs4M_41hUrwN2kaS6XCPydcwA9

    - name: Expose local server with Ngrok
      run: .\ngrok.exe http 8080  # Replace 8080 with the port of your local server
