name: Run Demo Batch File

on:
  push:
    branches:
      - main

jobs:
  run_demo_batch_file:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Demo Batch Script
      run: |
        @echo off
        cd C:\wamp64
        call demo.bat

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        # Your PowerShell commands here
